Repository OrchardCMS/OrchardCore, pull requests merged in 2018-12, with the labels that each got.

#2826 Configure the Users module to register the application cookie handler as the default sign-out scheme
  src/OrchardCore.Modules/OrchardCore.Users/Startup.cs
Labels: bug

#2834 Fix OpenIdApplicationStore.SetRolesAsync() to avoid saving the application entity and improve the application update view
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ApplicationController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ScopeController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/EditOpenIdApplicationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Edit.cshtml
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdApplicationStore.cs
Labels: Orchard.OpenId, bug

#2884 Fixing OpenId applications creation
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Create.cshtml
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs
Labels: Orchard.OpenId, P1, bug, ready

#2893 Update assets references to use app-relative paths
  src/OrchardCore.Modules/OrchardCore.AdminTrees/Views/Items/LinkAdminNode.Fields.TreeEdit.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminTrees/Views/Items/PlaceholderAdminNode.Fields.TreeEdit.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminTrees/Views/Node/List.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminTrees/Views/Tree/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminTrees/Views/Tree/List.cshtml
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentFields/Views/ContentPickerField.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentFields/Views/HtmlField-Wysiwyg.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentFields/Views/Media-HtmlField.Modal.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentFields/Views/NumericField-Slider.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentFields/Views/TextField-IconPicker.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentFields/Views/TextFieldPredefinedListEditorSettings.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentPreview/Views/ContentPreview.Button.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentPreview/Views/Preview/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Content.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentTypesAdminNode.Fields.TreeEdit.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/CreateContentTask.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Email/Views/Items/EmailTask.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Flows/Views/BagPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Flows/Views/FlowPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Html/Views/HtmlBodyPart-Wysiwyg.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Html/Views/Media-HtmlBodyPart.Modal.cshtml
  src/OrchardCore.Modules/OrchardCore.Liquid/Views/LiquidPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Lists/Views/Items/ListsAdminNode.Fields.TreeEdit.cshtml
  src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownBodyPart-Wysiwyg.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-Wysiwyg.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Markdown/Views/Media-MarkdownBodyPart.Modal.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/README.md
  src/OrchardCore.Modules/OrchardCore.Media/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/MediaField.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Menu/Views/MenuItem.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Menu/Views/MenuPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Resources/README.md
  src/OrchardCore.Modules/OrchardCore.Resources/ResourceManifest.cs
  src/OrchardCore.Modules/OrchardCore.Setup/Views/Setup/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Setup/Views/_Layout.cshtml
  src/OrchardCore.Modules/OrchardCore.Taxonomies/Views/TaxonomyPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Taxonomies/Views/Term.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Templates/Views/Preview/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Templates/Views/Template/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.Templates/Views/Template/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Tenants/Views/Admin/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.Tenants/Views/Admin/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Themes/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Widgets/Views/WidgetsListPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/HttpRequestTask.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/HttpResponseTask.Fields.Edit.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/Layout-Login.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml
  src/OrchardCore.Themes/TheComingSoonTheme/Views/layout.liquid
  src/OrchardCore.Themes/TheTheme/Views/Layout.cshtml
  src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/ResourceDefinition.cs
  src/OrchardCore/OrchardCore.ResourceManagement/ResourceManager.cs
  src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Theme/Views/Layout.liquid
  test/OrchardCore.Tests.Pages/OrchardCore.Themes.Pages/Theme.Pages/Views/Layout.cshtml
Labels: P0, bug

#2719 Improve the HTTPS module
  src/OrchardCore.Modules/OrchardCore.Https/Drivers/HttpsSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Https/OrchardCore.Https.csproj
  src/OrchardCore.Modules/OrchardCore.Https/Services/RewriteOptionsHttpsConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.Https/Settings/HttpsSettings.cs
  src/OrchardCore.Modules/OrchardCore.Https/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Https/ViewModels/HttpsSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Https/Views/HttpsSettings.Edit.cshtml
  src/OrchardCore/OrchardCore/Modules/Extensions/ApplicationBuilderExtensions.cs
  src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs
Labels: enhancement
