Repository OrchardCMS/OrchardCore, pull requests merged in 2018-06, with the labels that each got.

#1787 Migrate to OpenIddict RC3
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.OpenId.EntityFrameworkCore/Startup.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdValidationConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ApplicationController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ScopeController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/UserInfoController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Handlers/OpenIdApplicationRoleRemovedEventHandler.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/OrchardCore.OpenId.csproj
  src/OrchardCore.Modules/OrchardCore.OpenId/Recipes/OpenIdApplicationStep.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Services/OpenIdValidationService.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Tasks/OpenIdBackgroundTask.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/OrchardCore.Users.csproj
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Models/OpenIdApplication.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Models/OpenIdAuthorization.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Models/OpenIdScope.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Models/OpenIdToken.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdApplicationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdAuthorizationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdScopeStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdTokenStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Descriptors/OpenIdApplicationDescriptor.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Descriptors/OpenIdAuthorizationDescriptor.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Descriptors/OpenIdScopeDescriptor.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Descriptors/OpenIdTokenDescriptor.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdApplicationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdAuthorizationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdScopeManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdTokenManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Models/IOpenIdApplication.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Models/IOpenIdAuthorization.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Models/IOpenIdScope.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Models/IOpenIdToken.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Stores/IOpenIdApplicationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Stores/IOpenIdAuthorizationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Stores/IOpenIdScopeStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Stores/IOpenIdTokenStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdAuthorizationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdScopeManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdTokenManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Models/OpenIdApplication.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Models/OpenIdAuthorization.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Models/OpenIdScope.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Models/OpenIdToken.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdApplicationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdAuthorizationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdScopeStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdTokenStore.cs
Labels: Orchard.OpenId, enhancement

#2008 Custom Activity Title
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentCreatedEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentDeletedEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentPublishedEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentUpdatedEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentVersionedEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/CreateContentTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/DeleteContentTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/PublishContentTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/UnpublishContentTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/_ViewImports.cshtml
  src/OrchardCore.Modules/OrchardCore.Email/Views/Items/EmailTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Drivers/ActivityMetadataDisplay.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Services/ActivityLibrary.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/ViewModels/EditActivityMetadataViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/ActivityMetadata.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/CorrelateTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/ForEachTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/ForLoopTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/ForkTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/HttpRedirectTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/HttpRequestEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/HttpRequestFilterEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/HttpRequestTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/IfElseTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/JoinTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/LogTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/NotifyTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/ScriptTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/SetOutputTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/SetPropertyTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/SignalEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/TimerEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/UserTaskEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Items/WhileLoopTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/_ViewImports.cshtml
  src/OrchardCore/OrchardCore.Workflows.Abstractions/Helpers/ActivityExtensions.cs
  src/OrchardCore/OrchardCore.Workflows.Abstractions/Helpers/ServiceProviderExtensions.cs
  src/OrchardCore/OrchardCore.Workflows.Abstractions/Models/ActivityMetadata.cs
  src/OrchardCore/OrchardCore.Workflows.Abstractions/OrchardCore.Workflows.Abstractions.csproj
  test/OrchardCore.Tests/Workflows/WorkflowManagerTests.cs
Labels: Orchard.Workflows, ready

#2001 Dotnet new templates doc
  src/Templates/README.MD
  src/docs/assets/images/38450194-c617148a-39e7-11e8-95b0-2d35f43a6fad.png
  src/docs/assets/images/38450242-886933f6-39e8-11e8-896c-1f807e5530a0.png
  src/docs/assets/images/38450422-63670f1c-39eb-11e8-9c14-0743f0a4da42.png
  src/docs/assets/images/38450533-6c0fbc98-39ed-11e8-91a5-d26a1105b91a.png
  src/docs/assets/images/38450558-f4b83098-39ed-11e8-93c7-0fd9e5112dff.png
  src/docs/assets/images/38450628-31c8e2b0-39ef-11e8-9de7-c15f0c6544c5.png
  src/docs/assets/images/orchard-screencast-1.gif
  src/docs/assets/images/orchard-screencast-2.gif
Labels: documentation

#2015 Removing Polly package version from Forms module project
  src/OrchardCore.Modules/OrchardCore.Forms/OrchardCore.Forms.csproj
Labels: ready

#2024 Fix admin left menu by using click event instead of hover
  src/OrchardCore.Themes/TheAdmin/Assets/js/jquery.hoverIntent.min.js
  src/OrchardCore.Themes/TheAdmin/Assets/js/menu.js
  src/OrchardCore.Themes/TheAdmin/Assets/scss/TheAdmin.scss
  src/OrchardCore.Themes/TheAdmin/Views/NavigationItem-admin.cshtml
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.min.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
Labels: ready

#2026 Start working on nuget templates.
  .gitignore
  OrchardCore.sln
  src/Templates/OrchardCore.Cms.Templates/OrchardCore.Cms.Templates.csproj
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/.template.config.src/icon.png
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/.template.config.src/template.json
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/NLog.config
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/OrchardCore.Templates.Cms.Web.csproj
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/Program.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/Properties/launchSettings.json
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/Startup.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/.template.config.src/icon.png
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/.template.config.src/template.json
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Controllers/HomeController.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Drivers/MyTestPartDisplayDriver.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Handlers/MyTestPartHandler.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Manifest.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Migrations.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Models/MyTestPart.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/OrchardCore.Templates.Module.csproj
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Settings/MyTestPartSettings.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Settings/MyTestPartSettingsDisplayDriver.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Settings/MyTestPartSettingsViewModel.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Startup.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/ViewModels/MyTestPartViewModel.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Views/Home/Index.cshtml
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Views/MyTestPart.Edit.cshtml
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Views/MyTestPart.liquid
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Views/MyTestPartSettings.Edit.cshtml
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Views/MyTestPart_Summary.liquid
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Module/Views/_ViewImports.cshtml
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/.template.config.src/icon.png
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/.template.config.src/template.json
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/Manifest.cs
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/OrchardCore.Templates.Theme.csproj
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/Recipes/Theme.recipe.json
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/Views/Layout.liquid
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/Views/Menu.liquid
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/Views/MenuItem.liquid
  src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Theme/Views/MenuItemLink-LinkMenuItem.liquid
  src/Templates/OrchardCore.Templates.Cms.Web/NLog.config
  src/Templates/OrchardCore.Templates.Cms.Web/OrchardCore.Templates.Cms.Web.csproj
  src/Templates/OrchardCore.Templates.Module/OrchardCore.Templates.Module.csproj
  src/Templates/OrchardCore.Templates.Theme/OrchardCore.Templates.Theme.csproj
  src/Templates/README.MD
  src/docs/assets/images/templates/38450242-886933f6-39e8-11e8-896c-1f807e5530a0.png
Labels: notready

#2057 Adding Forms documentation
  mkdocs.yml
  src/OrchardCore.Modules/OrchardCore.Forms/Docs/contact-form-expanded-1.png
  src/OrchardCore.Modules/OrchardCore.Forms/Docs/contact-form-front-end-1.png
  src/OrchardCore.Modules/OrchardCore.Forms/Docs/contact-form-workflow-1.png
  src/OrchardCore.Modules/OrchardCore.Forms/README.md
Labels: documentation, ready

#2058 Adding custom title support to Forms activities
  src/OrchardCore.Modules/OrchardCore.Forms/Views/Items/AddModelValidationErrorTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Forms/Views/Items/BindModelStateTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Forms/Views/Items/ValidateAntiforgeryTokenTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Forms/Views/Items/ValidateFormFieldTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Forms/Views/Items/ValidateFormTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Forms/Views/Items/ValidateFormTask.Fields.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Forms/Views/Items/ValidateNoCaptchaTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Forms/Views/_ViewImports.cshtml
Labels: ready

#2059 Fixing ValidateFormTask
  src/OrchardCore.Modules/OrchardCore.Forms/Workflows/Activities/ValidateFormTask.cs
Labels: ready
