Repository OrchardCMS/OrchardCore, pull requests merged in 2019-10, with the labels that each got.

#4449 Allow sending email with the display name
  src/OrchardCore.Modules/OrchardCore.Email/Services/SmtpService.cs
  test/OrchardCore.Tests/Modules/OrchardCore.Email/EmailTests.cs
Labels: ready

#4424 Fix Blob double encoding issues with whitespace and accent characters
  src/OrchardCore.Modules/OrchardCore.Media/Services/MediaFileStoreResolverMiddleware.cs
Labels: ready

#4464 Add ability to generate DisplayText with a Pattern
  src/OrchardCore.Modules/OrchardCore.Autoroute/Views/AutoroutePartSettings.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Title/Drivers/TitlePartDisplay.cs
  src/OrchardCore.Modules/OrchardCore.Title/Handlers/TitlePartHandler.cs
  src/OrchardCore.Modules/OrchardCore.Title/Models/TitlePart.cs
  src/OrchardCore.Modules/OrchardCore.Title/Models/TitlePartSettings.cs
  src/OrchardCore.Modules/OrchardCore.Title/README.md
  src/OrchardCore.Modules/OrchardCore.Title/Settings/TitlePartSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Title/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Title/ViewModels/TitlePartSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Title/ViewModels/TitlePartViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Title/Views/TitlePart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Title/Views/TitlePartSettings.Edit.cshtml
Labels: ready

#4442 Avoid slash in role name
  src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs
Labels: ready

#4557 Migrate to OpenIddict 2.0.1
  src/OrchardCore.Build/Dependencies.props
Labels: Orchard.OpenId

#4554 TotalHits for Lucene Queries.
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/ApiController.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/GraphQL/LuceneQueryFieldTypeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneQuerySource.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/ViewModels/AdminQueryViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Admin/Query.cshtml
  src/OrchardCore.Modules/OrchardCore.Queries/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Controllers/ApiController.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Liquid/QueryFilter.cs
  src/OrchardCore.Modules/OrchardCore.Queries/QueryGlobalMethodProvider.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Razor/QueryOrchardRazorHelperExtensions.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Services/QueryManager.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Sql/GraphQL/SqlQueryFieldTypeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Sql/SqlQuerySource.cs
  src/OrchardCore/OrchardCore.Lucene.Abstractions/ILuceneQueryService.cs
  src/OrchardCore/OrchardCore.Lucene.Abstractions/LuceneTopDocs.cs
  src/OrchardCore/OrchardCore.Lucene.Core/LuceneQueryService.cs
  src/OrchardCore/OrchardCore.Queries.Abstractions/IQueryManager.cs
  src/OrchardCore/OrchardCore.Queries.Abstractions/IQueryResults.cs
  src/OrchardCore/OrchardCore.Queries.Abstractions/IQuerySource.cs
  src/OrchardCore/OrchardCore.Queries.Abstractions/LuceneQueryResults.cs
  src/OrchardCore/OrchardCore.Queries.Abstractions/SQLQueryResults.cs
Labels: Orchard.Lucene

#4565 Fix SiteSettings defaults
  src/OrchardCore.Modules/OrchardCore.Settings/Deployment/SiteSettingsDeploymentSource.cs
  src/OrchardCore.Modules/OrchardCore.Settings/Recipes/SettingsStep.cs
  src/OrchardCore.Modules/OrchardCore.Settings/SiteSettings.cs
  src/OrchardCore.Modules/OrchardCore.Settings/Views/Settings.Edit.cshtml
  src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/ResourceManagementOptions.cs
Labels: ready
