Repository OrchardCMS/OrchardCore, pull requests merged in 2019-12, with the labels that each got.

#4935 Fix graphql field queries on non-collapsed parts.
  src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Fields/ContentFieldsProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Fields/ObjectGraphTypeFieldProvider.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/DynamicContentTypeBuilder.cs
Labels: ready

#4934 Update graphiql.
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/package.json
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/webpack.config.js
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/wwwroot/Scripts/graphiql-orchard.js
Labels: ready

#3951 [GraphQL] Permissions
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Permissions.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/ValidationRules/RequiresPermissionValidationRule.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/Extensions/PermissionsExtensions.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/GraphQLPermissionContext.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/GraphQLSettings.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/OrchardCore.Apis.GraphQL.Abstractions.csproj
  src/OrchardCore/OrchardCore.Apis.GraphQL.Client/ContentResource.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/OrchardCore.ContentManagement.GraphQL.csproj
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentTypeQuery.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/TypedContentTypeBuilder.cs
  test/OrchardCore.Tests/Apis/Context/AuthenticationContext.cs
  test/OrchardCore.Tests/Apis/Context/BlogContext.cs
  test/OrchardCore.Tests/Apis/Context/SiteContext.cs
  test/OrchardCore.Tests/Apis/Context/SiteStartup.cs
  test/OrchardCore.Tests/Apis/GraphQL/Blog/BlogPostTests.cs
  test/OrchardCore.Tests/Apis/GraphQL/Client/ContentTypeQueryResourceBuilderTests.cs
  test/OrchardCore.Tests/Apis/GraphQL/Queries/RecentBlogPostsQueryTests.cs
  test/OrchardCore.Tests/Apis/GraphQL/ValidationRules/RequiresPermissionValidationRuleTests.cs
Labels: ready

#4495 Add ShapeDump
  src/OrchardCore.Themes/TheTheme/Views/Layout.cshtml
  src/OrchardCore/OrchardCore.ContentManagement.Display/Razor/OrchardRazorHelperExtensions.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Extensions/RazorHelperExtensions.cs
  src/OrchardCore/OrchardCore.DisplayManagement/IShape.cs
  src/OrchardCore/OrchardCore.DisplayManagement/OrchardCoreBuilderExtensions.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Shapes/ConsoleLogWrapperShapes.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Shapes/ShapeMetadata.cs
Labels: ready

#4353 Delete role should warn the user if the role has associated users
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Admin/Index.cshtml
Labels: ready

#4648 Add deployment step for Open ID
  src/OrchardCore.Modules/OrchardCore.OpenId/Deployment/OpenIdServerDeploymentSource.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Deployment/OpenIdServerDeploymentStep.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Deployment/OpenIdServerDeploymentStepDriver.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Items/OpenIdServerDeploymentStep.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Items/OpenIdServerDeploymentStep.Summary.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Items/OpenIdServerDeploymentStep.Thumbnail.cshtml
Labels: ready

#3809 Lucene Index Settings (Analyzers)
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/ContentPickerFieldIndexHandler.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Indexing/AspectsContentIndexHandler.cs
  src/OrchardCore.Modules/OrchardCore.Indexing/CreateIndexingTaskContentHandler.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/SearchController.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Deployment/LuceneIndexDeploymentSource.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Deployment/LuceneIndexDeploymentStepDriver.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Drivers/LuceneQueryDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Drivers/LuceneSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Handler/LuceneIndexingContentHandler.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/LuceneIndexingService.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Model/LuceneIndexSettings.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Model/LuceneSettings.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/OrchardCore.Lucene.csproj
  src/OrchardCore.Modules/OrchardCore.Lucene/Recipes/LuceneIndexStep.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/IndexingBackgroundTask.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneIndexManager.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneIndexSettingsService.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneIndexingService.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneIndexingState.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneQuerySource.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Settings/ContentPickerFieldLuceneEditorSettingsDriver.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Shapes/LuceneContentPickerShapeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/ViewModels/AdminEditViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/ViewModels/AdminIndexViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/ViewModels/IndexViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/ViewModels/LuceneIndexSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Admin/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Admin/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Admin/Query.cshtml
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Query-Lucene.Link.cshtml
  src/OrchardCore.Themes/TheAdmin/Assets/scss/TheAdmin.scss
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
  src/OrchardCore.Themes/TheBlogTheme/Recipes/Snippets/recentBlogPosts.json
  src/OrchardCore.Themes/TheBlogTheme/Recipes/blog.recipe.json
  src/OrchardCore/OrchardCore.Application.Cms.Core.Targets/OrchardCore.Application.Cms.Core.Targets.csproj
  src/OrchardCore/OrchardCore.Contents.Core/Indexing/IndexingConstants.cs
  src/OrchardCore/OrchardCore.Data/Migration/DataMigrationManager.cs
  src/OrchardCore/OrchardCore.Indexing.Abstractions/ContentFieldIndexHandler.cs
  src/OrchardCore/OrchardCore.Lucene.Core/QueryProviders/BooleanQueryProvider.cs
  src/OrchardCore/OrchardCore.Lucene.Core/QueryProviders/RangeQueryProvider.cs
  src/OrchardCore/OrchardCore.Mvc.Core/Utilities/StringExtensions.cs
Labels: Orchard.Lucene

#5121 GetDictionary() should be called once per culture
  src/OrchardCore/OrchardCore.Localization.Core/PortableObject/PortableObjectStringLocalizer.cs
  test/OrchardCore.Tests/Localization/PortableObjectStringLocalizerTests.cs
Labels: localization, perf

#5060 Liquid console_log filter and docs
  src/OrchardCore.Modules/OrchardCore.DynamicCache/CachedShapeWrapperShapes.cs
  src/OrchardCore/OrchardCore.ContentManagement.Display/Liquid/ConsoleLogFilter.cs
  src/OrchardCore/OrchardCore.ContentManagement.Display/Razor/OrchardRazorHelperExtensions.cs
  src/OrchardCore/OrchardCore.ContentManagement.Display/ServiceCollectionExtensions.cs
  src/OrchardCore/OrchardCore.DisplayManagement/IShape.cs
  src/OrchardCore/OrchardCore.DisplayManagement/OrchardCoreBuilderExtensions.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Shapes/ConsoleLogWrapperShapes.cs
  src/docs/reference/modules/Contents/README.md
Labels: ready

#5050 Localizer should work with inner classes as well
  src/OrchardCore/OrchardCore.Localization.Core/PortableObject/PortableObjectStringLocalizerFactory.cs
  test/OrchardCore.Tests/Localization/PoFiles/ar.po
  test/OrchardCore.Tests/Localization/PortableObjectStringLocalizerFactoryTests.cs
  test/OrchardCore.Tests/Stubs/StubPoFileLocationProvider.cs
Labels: localization, ready
