Repository OrchardCMS/OrchardCore, pull requests merged in 2019-01, with the labels that each got.

#2973 Prevent liquid tag helper conflicts.
  src/OrchardCore.Themes/TheBlogTheme/Views/Layout.liquid
  src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs
  src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/IResourceManager.cs
  src/OrchardCore/OrchardCore.ResourceManagement/ResourceManager.cs
  src/OrchardCore/OrchardCore.ResourceManagement/TagHelpers/ScriptTagHelper.cs
  src/OrchardCore/OrchardCore.ResourceManagement/TagHelpers/StyleTagHelper.cs
Labels: notready

#2989 Add documentation on adding html attributes on img_tag liquid filter
  src/OrchardCore.Modules/OrchardCore.Media/README.md
Labels: ready

#2992 fixes admin menu animations
  src/OrchardCore.Themes/TheAdmin/Assets/js/menu.js
  src/OrchardCore.Themes/TheAdmin/Assets/scss/TheAdmin.scss
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.min.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
Labels: ready

#2986 Localizations files search paths
  src/OrchardCore.Modules/OrchardCore.Localization/ModularPoFileLocationProvider.cs
  src/OrchardCore.Modules/OrchardCore.Localization/README.md
Labels: ready

#2886 Remove the testing mode feature and replace it by automatic signing certificate generation
  src/OrchardCore.Build/Dependencies.AspNetCore.props
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.OpenId/AdminMenu.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdValidationConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ServerConfigurationController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ValidationConfigurationController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Drivers/OpenIdServerSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Drivers/OpenIdValidationSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/OrchardCore.OpenId.csproj
  src/OrchardCore.Modules/OrchardCore.OpenId/Recipes/OpenIdServerSettingsStep.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Services/IOpenIdServerService.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Services/OpenIdServerService.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Services/OpenIdValidationService.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Settings/OpenIdServerSettings.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Tasks/OpenIdBackgroundTask.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/OpenIdServerSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/OpenIdServerSettings.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/ServerConfiguration/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/ValidationConfiguration/Index.cshtml
  src/OrchardCore/OrchardCore.AdminMenu.Abstractions/OrchardCore.AdminMenu.Abstractions.csproj
  src/OrchardCore/OrchardCore.DisplayManagement/OrchardCore.DisplayManagement.csproj
  src/OrchardCore/OrchardCore.Email.Abstractions/OrchardCore.Email.Abstractions.csproj
Labels: Orchard.OpenId, enhancement

#3084 [GraphQL] Multiple alias names with the same index
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentItemsFieldType.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/IndexAlias.cs
  test/OrchardCore.Tests/Apis/GraphQL/ContentItemsFieldTypeTests.cs
Labels: bug

#2842 [GraphQL] Option to collapse parts
  src/OrchardCore.Modules/OrchardCore.Autoroute/Startup.cs
  src/OrchardCore.Modules/OrchardCore.ContentTypes/GraphQL/Drivers/GraphQLContentTypePartSettingsDriver.cs
  src/OrchardCore.Modules/OrchardCore.ContentTypes/GraphQL/Startup.cs
  src/OrchardCore.Modules/OrchardCore.ContentTypes/GraphQL/ViewModels/GraphQLContentTypePartSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.ContentTypes/OrchardCore.ContentTypes.csproj
  src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/GraphQLContentTypePartSettings.Edit.cshtml
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Extensions/ServiceCollectionExtensions.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Options/GraphQLContentOptions.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/OrchardCore.ContentManagement.GraphQL.csproj
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/DynamicContentTypeBuilder.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/TypedContentTypeBuilder.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/ServiceCollectionExtensions.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Settings/GraphQLContentTypePartSettings.cs
Labels: enhancement, ready
