Repository OrchardCMS/OrchardCore, pull requests merged in 2020-01, with the labels that each got.

#5203 Fix remaining routes to AdminUrlPrefix
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Startup.cs
  src/OrchardCore.Modules/OrchardCore.BackgroundTasks/Startup.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Demo/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Features/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Flows/OrchardCore.Flows.csproj
  src/OrchardCore.Modules/OrchardCore.Flows/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Media/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Recipes/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Taxonomies/OrchardCore.Taxonomies.csproj
  src/OrchardCore.Modules/OrchardCore.Taxonomies/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Templates/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Themes/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Themes/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Widgets/OrchardCore.Widgets.csproj
  src/OrchardCore.Modules/OrchardCore.Widgets/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Startup.cs
Labels: ready

#5294 Provide new AddOrchardCms/AddOrchardCore overloads
  src/OrchardCore/OrchardCore.Application.Cms.Core.Targets/ServiceExtensions.cs
  src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#5195 Get draft content item by alias
  src/OrchardCore.Modules/OrchardCore.Alias/Drivers/AliasPartDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Alias/Handlers/AliasPartHandler.cs
  src/OrchardCore.Modules/OrchardCore.Alias/Indexes/AliasPartIndex.cs
  src/OrchardCore.Modules/OrchardCore.Alias/Migrations.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Razor/ContentRazorHelperExtensions.cs
Labels: ready

#5293 Remove OrchardCore.OpenId.EntityFrameworkCore and OrchardCore.OpenId.Core.EntityFrameworkCore
  OrchardCore.sln
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.OpenId.EntityFrameworkCore/Manifest.cs
  src/OrchardCore.Modules/OrchardCore.OpenId.EntityFrameworkCore/OrchardCore.OpenId.EntityFrameworkCore.csproj
  src/OrchardCore.Modules/OrchardCore.OpenId.EntityFrameworkCore/Startup.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ApplicationController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Handlers/OpenIdApplicationRoleRemovedEventHandler.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Users/Controllers/AccountController.cs
  src/OrchardCore.Modules/OrchardCore.Users/OrchardCore.Users.csproj
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/OrchardCore.OpenId.Core.EntityFrameworkCore.csproj
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdApplicationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdAuthorizationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdScopeStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdTokenStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdApplicationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdAuthorizationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdScopeManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Abstractions/Managers/IOpenIdTokenManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/OpenIdExtensions.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdAuthorizationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdScopeManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdTokenManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Indexes/OpenIdApplicationIndex.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Resolvers/OpenIdApplicationStoreResolver.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Resolvers/OpenIdAuthorizationStoreResolver.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Resolvers/OpenIdScopeStoreResolver.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Resolvers/OpenIdTokenStoreResolver.cs
Labels: Orchard.OpenId, enhancement, ready

#5308 Update the OpenID YesSql stores to execute a concurrency check on updates
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdApplicationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdAuthorizationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdScopeStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdTokenStore.cs
Labels: Orchard.OpenId, enhancement

#5336 Move OpenIdServer deployment services to ServerStatup to fix bug in d…
  src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs
Labels: Orchard.OpenId, bug

#5225 IAreaControllerRouteMapper
  src/OrchardCore.Modules/OrchardCore.Admin/AdminActionConstraint.cs
  src/OrchardCore.Modules/OrchardCore.Admin/AdminActionConstraintFactory.cs
  src/OrchardCore.Modules/OrchardCore.Admin/AdminActionModelConvention.cs
  src/OrchardCore.Modules/OrchardCore.Admin/AdminAreaControllerRouteMapper.cs
  src/OrchardCore.Modules/OrchardCore.Admin/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Demo/Manifest.cs
  src/OrchardCore/OrchardCore.Mvc.Core/Routing/DefaultAreaControllerRouteMapper.cs
  src/OrchardCore/OrchardCore.Mvc.Core/Routing/IAreaControllerRouteMapper.cs
  src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs
Labels: ready

#5207 Preserve query string in language switcher
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Controllers/ContentCulturePickerController.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Liquid/SwitchCultureUrlFilter.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Views/ContentCulturePickerContainer.cshtml
Labels: ready

#5326 Adding User Disabled/Enabled Events
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UserDisabledEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UserDisabledEvent.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UserDisabledEvent.Fields.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UserEnabledEvent.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UserEnabledEvent.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UserEnabledEvent.Fields.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Activities/UserCreatedEvent.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Activities/UserDisabledEvent.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Activities/UserEnabledEvent.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Drivers/UserCreatedEventDisplay.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Drivers/UserDisabledEventDisplay.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Drivers/UserEnabledEventDisplay.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Drivers/UserLoggedInEventDisplay.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Handlers/UserEventHandler.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/ViewModels/UserDisabledEventViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/Workflows/ViewModels/UserEnabledEventViewModel.cs
  src/OrchardCore/OrchardCore.Users.Abstractions/Handlers/CreateUserContext.cs
  src/OrchardCore/OrchardCore.Users.Abstractions/Handlers/IUserCreatedEventHandler.cs
  src/OrchardCore/OrchardCore.Users.Abstractions/Handlers/IUserEventHandler.cs
  src/OrchardCore/OrchardCore.Users.Abstractions/Handlers/UserContext.cs
  src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs
Labels: ready

#5169 Trumbowyg culture direction
  src/OrchardCore.Modules/OrchardCore.Html/Views/HtmlBodyPart-Trumbowyg.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Html/Views/HtmlBodyPart-Wysiwyg.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Localization/Views/LocalizationSettings.Edit.cshtml
Labels: ready
