Repository OrchardCMS/OrchardCore, pull requests merged in 2020-11, with the labels that each got.

#7406 CI Testing across SQL MySql and Postgres databases
  appveyor.yml
  src/OrchardCore.Build/Dependencies.props
  test/OrchardCore.Tests/Apis/ContentManagement/ContentApiController/BlogPostApiControllerTests.cs
  test/OrchardCore.Tests/Apis/ContentManagement/DeploymentPlans/BlogPostContentStepIdempotentTests.cs
  test/OrchardCore.Tests/Apis/ContentManagement/DeploymentPlans/BlogPostCreateDeploymentPlanTests.cs
  test/OrchardCore.Tests/Apis/ContentManagement/DeploymentPlans/BlogPostValidateDeploymentPlanTests.cs
  test/OrchardCore.Tests/Apis/Context/AgencyContext.cs
  test/OrchardCore.Tests/Apis/Context/Attributes/MySqlDataAttribute.cs
  test/OrchardCore.Tests/Apis/Context/Attributes/PostgreSqlDataAttribute.cs
  test/OrchardCore.Tests/Apis/Context/Attributes/SqlServerDataAttribute.cs
  test/OrchardCore.Tests/Apis/Context/Attributes/SqliteDataAttribute.cs
  test/OrchardCore.Tests/Apis/Context/BlogContext.cs
  test/OrchardCore.Tests/Apis/Context/BlogPostApiControllerContext.cs
  test/OrchardCore.Tests/Apis/Context/BlogPostDeploymentContext.cs
  test/OrchardCore.Tests/Apis/Context/SiteContext.cs
  test/OrchardCore.Tests/Apis/Context/TablePrefixGenerator.cs
  test/OrchardCore.Tests/Apis/Context/TablePrefixGeneratorTests.cs
  test/OrchardCore.Tests/Apis/GraphQL/Blog/BlogPostTests.cs
  test/OrchardCore.Tests/Apis/Recipes/AgencyRecipeTests.cs
  test/OrchardCore.Tests/Apis/Recipes/BlogRecipeTests.cs
  test/OrchardCore.Tests/Apis/Recipes/ComingSoonRecipeTests.cs
  test/OrchardCore.Tests/Apis/Recipes/HeadlessRecipeTests.cs
  test/OrchardCore.Tests/ResourceManagement/ResourceManagerTests.cs
Labels: ready

#7393 Document Options and Compression
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.Redis/Services/RedisLock.cs
  src/OrchardCore/OrchardCore.Abstractions/Locking/ILocker.cs
  src/OrchardCore/OrchardCore.Abstractions/Locking/LockerExtensions.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Documents/IDocumentManager.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Documents/IDocumentSerialiser.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Documents/IVolatileDocumentManager.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Documents/Options/DocumentOptions.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Documents/Options/IDocumentOptionsFactory.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/DefaultDocumentSerializer.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/DocumentManager.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/DocumentManagerOfT.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/Options/DocumentOptionsFactory.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/Options/DocumentOptionsOfT.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/Options/DocumentOptionsSetup.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/OrchardCoreBuilderExtensions.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/VolatileDocumentManager.cs
  src/OrchardCore/OrchardCore/Locking/LocalLock.cs
  test/OrchardCore.Tests/Routing/AutorouteEntriesTests.cs
Labels: notready

#7470 Mikekry/6136 not mandatory localizationset
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/GraphQL/LocalizationInputObjectType.cs
Labels: ready

#4232 Cypress testing
  appveyor.yml
  test/Functional/.gitignore
  test/Functional/OrchardCore.FunctionalTests.csproj
  test/Functional/Readme.md
  test/Functional/cms-tests/cypress.json
  test/Functional/cms-tests/cypress/integration/000-sass-setup.js
  test/Functional/cms-tests/cypress/integration/agency-test.js
  test/Functional/cms-tests/cypress/integration/blog-test.js
  test/Functional/cms-tests/cypress/plugins/index.js
  test/Functional/cms-tests/cypress/support/commands.js
  test/Functional/cms-tests/cypress/support/index.js
  test/Functional/cypress-commands/.npmignore
  test/Functional/cypress-commands/LICENSE
  test/Functional/cypress-commands/README.md
  test/Functional/cypress-commands/dist/index.js
  test/Functional/cypress-commands/dist/index.mjs
  test/Functional/cypress-commands/dist/test-runner.js
  test/Functional/cypress-commands/dist/test-runner.mjs
  test/Functional/cypress-commands/dist/utils.js
  test/Functional/cypress-commands/dist/utils.mjs
  test/Functional/cypress-commands/package-lock.json
  test/Functional/cypress-commands/package.json
  test/Functional/cypress-commands/rollup.config.js
  test/Functional/cypress-commands/src/buttons.js
  test/Functional/cypress-commands/src/configuration.js
  test/Functional/cypress-commands/src/cySelectors.js
  test/Functional/cypress-commands/src/features.js
  test/Functional/cypress-commands/src/index.js
  test/Functional/cypress-commands/src/recipe.js
  test/Functional/cypress-commands/src/tenants.js
  test/Functional/cypress-commands/src/test-runner.js
  test/Functional/cypress-commands/src/urls.js
  test/Functional/cypress-commands/src/utils.js
  test/Functional/mvc-tests/cypress.json
  test/Functional/mvc-tests/cypress/integration/mvc-test.js
  test/Functional/mvc-tests/cypress/plugins/index.js
  test/Functional/mvc-tests/cypress/support/commands.js
  test/Functional/mvc-tests/cypress/support/index.js
  test/Functional/orchard.js
  test/Functional/package-lock.json
  test/Functional/package.json
  test/Functional/samples-mvc.test.js
  test/Functional/setup.test.js
  test/Functional/test-run.cmd
  test/Functional/test-setup.cmd
  test/Functional/test_generator.js
Labels: ready

#7485 Update Jint and add unit test
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore/OrchardCore.Scripting.JavaScript/JavaScriptEngine.cs
Labels: ready

#7590 Allow multiple email authors
  src/OrchardCore.Modules/OrchardCore.Email/Services/SmtpService.cs
  test/OrchardCore.Tests/Modules/OrchardCore.Email/EmailTests.cs
Labels: ready

#7593 ReplyTo must have author addresses if not set
  src/OrchardCore.Modules/OrchardCore.Email/Services/SmtpService.cs
  test/OrchardCore.Tests/Modules/OrchardCore.Email/EmailTests.cs
Labels: ready

#7556 Custom User Settings
  mkdocs.yml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/AdminTabs.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Card.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Tab.cshtml
  src/OrchardCore.Modules/OrchardCore.Demo/Drivers/UserProfileDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Demo/Permissions.cs
  src/OrchardCore.Modules/OrchardCore.Users/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Users/CustomUserSettingsPermissions.cs
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/CustomUserSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserInformationDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Manifest.cs
  src/OrchardCore.Modules/OrchardCore.Users/Permissions.cs
  src/OrchardCore.Modules/OrchardCore.Users/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/CustomUserSettingsEditViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/EditUserInformationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/EditUserViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/Views/Admin/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/CustomUserSettings.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/CustomUserSettings.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserFields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserInformationFields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenu.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/_ViewImports.cshtml
  src/OrchardCore/OrchardCore.Users.Core/CommonPermissions.cs
  src/docs/reference/modules/Users/Configuration/README.md
  src/docs/reference/modules/Users/CustomUserSettings/README.md
Labels: ready

#7117 Enhance Docker story
  .dockerignore
  Dockerfile
Labels: ready

#7675 Bump OpenIddict to 3.0.0-rc1.20567.82
  .github/workflows/functional_all_db.yml
  .github/workflows/mac_unit_test_ci.yml
  .github/workflows/pr_ci.yml
  .github/workflows/release_ci.yml
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdAuthorizationManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdScopeManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdTokenManager.cs
Labels: OpenId, bug, ready

#7511 Admin Menu Permissions
  src/OrchardCore.Modules/OrchardCore.AdminMenu/AdminNodes/LinkAdminNodeDriver.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/AdminNodes/LinkAdminNodeNavigationBuilder.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/AdminNodes/LinkAdminNodeViewModel.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/AdminNodes/PlaceholderAdminNodeDriver.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/AdminNodes/PlaceholderAdminNodeNavigationBuilder.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/AdminNodes/PlaceholderAdminNodeViewModel.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets.json
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/js/vue-multiselect-permission-picker.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/scss/vue-multiselect-permission-picker.scss
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Controllers/NodeController.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Startup.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/ViewModels/VueMultiselectItemViewModel.cs
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/Items/LinkAdminNode.Fields.TreeEdit.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/Items/PlaceholderAdminNode.Fields.TreeEdit.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/vue-multiselect-permission-picker.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/vue-multiselect-permission-picker.min.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/vue-multiselect-wrapper.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/vue-multiselect-wrapper.min.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/vue-multiselect-permission-picker.css
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/vue-multiselect-permission-picker.min.css
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/vue-multiselect-wrapper.css
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/vue-multiselect-wrapper.min.css
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Security/Permissions/Permission.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Security/Services/IPermissionsService.cs
  src/OrchardCore/OrchardCore.Infrastructure/Security/Services/DefaultPermissionsService.cs
  src/OrchardCore/OrchardCore.Navigation.Core/NavigationManager.cs
Labels: ready

#7605 Dark mode V2 (cookie based)
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets.json
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/js/fontawesome-iconpicker.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/scss/admin-menu-icon-picker.scss
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/scss/fontawesome-iconpicker.scss
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/scss/vue-multiselect-permission-picker.scss
  src/OrchardCore.Modules/OrchardCore.AdminMenu/package-lock.json
  src/OrchardCore.Modules/OrchardCore.AdminMenu/package.json
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/admin-menu-icon-picker.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/admin-menu-icon-picker.min.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/admin-menu-icon-picker.css
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/admin-menu-icon-picker.min.css
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Assets/css/graphiql-orchard.css
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminList.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment/Views/DeploymentPlan/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Assets/scss/media.scss
  src/OrchardCore.Modules/OrchardCore.Media/package.json
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Styles/media.css
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Styles/media.min.css
  src/OrchardCore.Modules/OrchardCore.Resources/package.json
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/jquery.easing.js
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/jquery.easing.min.js
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Styles/trumbowyg-plugins.css
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Styles/trumbowyg-plugins.min.css
  src/OrchardCore.Modules/OrchardCore.Setup/package.json
  src/OrchardCore.Modules/OrchardCore.Tenants/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Themes/Services/DarkModeService.cs
  src/OrchardCore.Modules/OrchardCore.Themes/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Users/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Workflow/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/WorkflowType/Index.cshtml
  src/OrchardCore.Themes/TheAdmin/Assets.json
  src/OrchardCore.Themes/TheAdmin/Assets/js/darkmode.js
  src/OrchardCore.Themes/TheAdmin/Assets/js/header/userPreferencesLoader.js
  src/OrchardCore.Themes/TheAdmin/Assets/js/userPreferencesPersistor.js
  src/OrchardCore.Themes/TheAdmin/Assets/scss/admin-darkmode.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/admin.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/_layout.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/theme/darkmode/_bootswatch.scss
  src/OrchardCore.Themes/TheAdmin/TheAdmin.csproj
  src/OrchardCore.Themes/TheAdmin/Views/Layout-Login.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/_ViewImports.cshtml
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin-header.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin-header.min.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.min.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin-darkmode.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin-darkmode.min.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
  src/OrchardCore/OrchardCore.Admin.Abstractions/Models/AdminSettings.cs
Labels: ready
