Repository OrchardCMS/OrchardCore, pull requests merged in 2020-09, with the labels that each got.

#6068 Configure Cookie Life Time for CulturePicker
  src/OrchardCore.Cms.Web/appsettings.json
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Controllers/ContentCulturePickerController.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/CulturePickerOptions.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Startup.cs
Labels: ready

#6700 Avoid creating empty templates
  src/OrchardCore.Modules/OrchardCore.Templates/Controllers/TemplateController.cs
  src/OrchardCore.Modules/OrchardCore.Templates/Views/Template/Create.cshtml
Labels: ready

#6230 Add PluralFormNotFoundException metadata
  src/OrchardCore/OrchardCore.Localization.Abstractions/CultureDictionary.cs
  src/OrchardCore/OrchardCore.Localization.Abstractions/PluralForm.cs
  src/OrchardCore/OrchardCore.Localization.Abstractions/PluralFormNotFoundException.cs
  test/OrchardCore.Tests/Localization/CultureDictionaryTests.cs
Labels: ready

#7101 ImageSharp.Web RTM
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.Media/Filters/MediaFilters.cs
  src/OrchardCore.Modules/OrchardCore.Media/Processing/ImageSharpUrlFormatter.cs
  src/OrchardCore.Modules/OrchardCore.Media/Processing/ImageVersionProcessor.cs
  src/OrchardCore.Modules/OrchardCore.Media/Processing/MediaImageSharpConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.Media/Processing/MediaResizingFileProvider.cs
  src/OrchardCore.Modules/OrchardCore.Media/Razor/OrchardRazorHelperExtensions.cs
  src/OrchardCore.Modules/OrchardCore.Media/Shortcodes/ImageShortcodeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Media/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Media/TagHelpers/ImageResizeTagHelper.cs
  src/docs/reference/modules/Media/README.md
Labels: ready

#7135 Fix OpenIdApplicationStep to honor AllowLogoutEndpoint
  src/OrchardCore.Modules/OrchardCore.OpenId/Recipes/OpenIdApplicationStep.cs
Labels: OpenId, bug

#7144 Setup : cleanup code
  src/OrchardCore.Modules/OrchardCore.Setup/Assets/js/setup.js
  src/OrchardCore.Modules/OrchardCore.Setup/Assets/scss/setup.scss
  src/OrchardCore.Modules/OrchardCore.Setup/Views/Setup/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Setup/wwwroot/Scripts/setup.js
  src/OrchardCore.Modules/OrchardCore.Setup/wwwroot/Scripts/setup.min.js
  src/OrchardCore.Modules/OrchardCore.Setup/wwwroot/Styles/setup.css
  src/OrchardCore.Modules/OrchardCore.Setup/wwwroot/Styles/setup.min.css
Labels: ready

#6980 Remove 'ManageOwnMedia' permission
  src/OrchardCore.Modules/OrchardCore.Media/AdminMenu.cs
  src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Media/Permissions.cs
  src/OrchardCore.Modules/OrchardCore.Media/Services/AttachedMediaFieldsFolderAuthorizationHandler.cs
Labels: ready

#5588 Use dropdown menu on admin top navbar for user menu
  src/OrchardCore.Modules/OrchardCore.Features/Views/Admin/Features.cshtml
  src/OrchardCore.Themes/TheAdmin/Assets/scss/TheAdmin.scss
  src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/UserMenu.cshtml
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
Labels: ready

#6903 Add option to allow Lucene query syntax in search
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/SearchController.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Drivers/LuceneSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Model/LuceneSettings.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/ViewModels/LuceneSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/LuceneSettings.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Search/Search.cshtml
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/_ViewImports.cshtml
  src/OrchardCore.Themes/TheAgencyTheme/Views/Shared/Search.liquid
  src/OrchardCore.Themes/TheBlogTheme/Views/Shared/Search.liquid
Labels: Lucene
