Repository OrchardCMS/OrchardCore, pull requests merged in 2020-12, with the labels that each got.

#7336 Make content items action bar sticky on scrolling
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminList-Create.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminList-Search.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminList.cshtml
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/admin/_navbar.scss
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
Labels: ready

#7894 Bump OpenIddict to 3.0.0-rc2.20607.88
  src/OrchardCore.Build/Dependencies.props
Labels: OpenId, dependencies

#6202 Make CultureDictionary IEnumerable
  src/OrchardCore/OrchardCore.Localization.Abstractions/CultureDictionary.cs
  test/OrchardCore.Tests/Localization/CultureDictionaryTests.cs
Labels: ready

#8106 Admin UI : Fix trumbowyg font-color on fullscreen in darkmode
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/theme/darkmode/_bootswatch.scss
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
Labels: ready

#8042 Correctly generate cdn base url for local scripts
  src/OrchardCore/OrchardCore.DisplayManagement.Liquid/Filters/ResourceUrlFilter.cs
  src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/ResourceDefinition.cs
  src/OrchardCore/OrchardCore.ResourceManagement/Razor/ResourceCdnHelperExtensions.cs
  test/OrchardCore.Tests/ResourceManagement/ResourceDefinitionTests.cs
Labels: ready

#8143 Bump OpenIddict to 3.0.0
  src/OrchardCore.Build/Dependencies.props
  src/docs/resources/libraries/README.md
Labels: OpenId, dependencies

#8132 Add credential overloads to Key Vault Configuration
  src/OrchardCore/OrchardCore.Configuration.KeyVault/Extensions/AzureKeyVaultWebHostBuilderExtension.cs
Labels: ready

#8083 Admin UI: Header buttons
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenu.cshtml
  src/OrchardCore.Themes/TheAdmin/Assets/scss/admin.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/mixins/_sizes.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/_layout.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/admin/_navbar.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/theme/darkmode/_bootswatch.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/theme/default/_bootswatch.scss
  src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
Labels: ready

#8142 Create ManageMediaOptions Permission
  src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Media/Permissions.cs
Labels: ready

#8156 bootstrap select and slider style resource
  src/OrchardCore.Modules/OrchardCore.Resources/ResourceManifest.cs
Labels: dontmerge

#8102 Fix modal semantics
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/Menu/List.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/MenuItem.TreeSummary.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/Node/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.BackgroundTasks/Views/BackgroundTask/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Views/LocalizationPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Views/LocalizationPart.SummaryAdminLinks.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/Admin/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/Admin/EditPart.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsButtonActions_SummaryAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/Download-Button-Actions.SummaryAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteClient/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteInstance/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment/Views/DeploymentPlan/Display.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment/Views/DeploymentPlan/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment/Views/DeploymentStep.Summary.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment/Views/Step/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Features/Views/Admin/Features.cshtml
  src/OrchardCore.Modules/OrchardCore.Layers/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Lists/Views/ListPart.DetailAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Lucene/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/MediaCache/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/MediaProfiles/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Menu/Views/MenuItem.Admin.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Scope/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Placements/Views/Admin/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Placements/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Placements/Views/Shared/DisplayTemplates/ShapePlacementViewModel.cshtml
  src/OrchardCore.Modules/OrchardCore.Queries/Views/Query.Buttons.SummaryAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Recipes/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Setup/Views/Setup/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/Admin/List.cshtml
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/SitemapCache/List.cshtml
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/SitemapIndex/List.cshtml
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/SitemapSource.SummaryAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/Source/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Taxonomies/Views/Content.TermAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Templates/Views/Template/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Themes/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserButtons.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Workflow/Details.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Workflow/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/WorkflowType/Index.cshtml
  src/OrchardCore.Themes/TheAdmin/Assets/js/admin.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.min.js
Labels: ready

#8162 Ability to deploy shortcode templates
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Deployment/AllShortcodeTemplatesDeploymentSource.cs
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Deployment/AllShortcodeTemplatesDeploymentStep.cs
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Deployment/AllShortcodeTemplatesDeploymentStepDriver.cs
  src/OrchardCore.Modules/OrchardCore.Shortcodes/OrchardCore.Shortcodes.csproj
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Recipes/ShortcodeTemplateStep.cs
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Items/AllShortcodeTemplatesDeploymentStep.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Items/AllShortcodeTemplatesDeploymentStep.Summary.cshtml
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Items/AllShortcodeTemplatesDeploymentStep.Thumbnail.cshtml
Labels: ready
