Repository OrchardCMS/OrchardCore, pull requests merged in 2020-10, with the labels that each got.

#7129 Prevent disabling or removing administrator role
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserFields.Edit.cshtml
Labels: ready

#7182 Small update to the docs for layers
  src/docs/reference/modules/Layers/README.md
Labels: documentation

#7204 Bump OpenIddict to 3.0.0-beta5.20503.76 and fix a bug in OpenIdApplicationManager
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs
Labels: OpenId, bug, dependencies

#6185 Expose Route property on Request object
  src/OrchardCore/OrchardCore.DisplayManagement.Liquid/RequestLiquidTemplateEventHandler.cs
  src/docs/reference/modules/Liquid/README.md
Labels: enhancement

#7196 Fix Lucene numHits must be > 0
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Services/SearchQueryService.cs
  src/OrchardCore/OrchardCore.Lucene.Core/LuceneQueryService.cs
Labels: ready

#7119 Media profiles feature
  src/OrchardCore.Modules/OrchardCore.Media/AdminMenu.cs
  src/OrchardCore.Modules/OrchardCore.Media/Controllers/MediaProfilesController.cs
  src/OrchardCore.Modules/OrchardCore.Media/Deployment/AllMediaProfilesDeploymentSource.cs
  src/OrchardCore.Modules/OrchardCore.Media/Deployment/AllMediaProfilesDeploymentStep.cs
  src/OrchardCore.Modules/OrchardCore.Media/Deployment/AllMediaProfilesDeploymentStepDriver.cs
  src/OrchardCore.Modules/OrchardCore.Media/Filters/MediaFilters.cs
  src/OrchardCore.Modules/OrchardCore.Media/Models/MediaProfilesDocument.cs
  src/OrchardCore.Modules/OrchardCore.Media/Permissions.cs
  src/OrchardCore.Modules/OrchardCore.Media/Processing/ImageSharpUrlFormatter.cs
  src/OrchardCore.Modules/OrchardCore.Media/Processing/MediaImageSharpConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.Media/Razor/OrchardRazorHelperExtensions.cs
  src/OrchardCore.Modules/OrchardCore.Media/Recipes/MediaProfileStep.cs
  src/OrchardCore.Modules/OrchardCore.Media/Services/IMediaProfileService.cs
  src/OrchardCore.Modules/OrchardCore.Media/Services/MediaProfileService.cs
  src/OrchardCore.Modules/OrchardCore.Media/Services/MediaProfilesManager.cs
  src/OrchardCore.Modules/OrchardCore.Media/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Media/TagHelpers/ImageResizeTagHelper.cs
  src/OrchardCore.Modules/OrchardCore.Media/ViewModels/MediaProfileIndexViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Media/ViewModels/MediaProfileViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Media/Views/Items/AllMediaProfilesDeploymentStep.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/Items/AllMediaProfilesDeploymentStep.Summary.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/Items/AllMediaProfilesDeploymentStep.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/MediaProfiles/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/MediaProfiles/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/MediaProfiles/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Views/_ViewImports.cshtml
  src/OrchardCore.Themes/TheAgencyTheme/Recipes/Snippets/landingpage.liquid
  src/OrchardCore.Themes/TheAgencyTheme/Recipes/agency.recipe.json
  src/OrchardCore.Themes/TheBlogTheme/Recipes/blog.recipe.json
  src/OrchardCore.Themes/TheBlogTheme/Views/Content-Article.liquid
  src/OrchardCore.Themes/TheBlogTheme/Views/Content-Blog.liquid
  src/OrchardCore.Themes/TheBlogTheme/Views/Content-BlogPost.liquid
  src/docs/reference/modules/Media/README.md
Labels: ready

#7169 Admin UI : responsive behaviors
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets.json
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/js/resizeTableBody.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Assets/scss/admin-menu.scss
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/Menu/List.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/MenuItem.TreeSummary.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/Node/List.cshtml
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/admin-menu.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Scripts/admin-menu.min.js
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/admin-menu.css
  src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/admin-menu.min.css
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminList.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsButtonEdit_SummaryAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/AddToDeploymentPlan-ActionDeploymentPlan.Modal.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/AddToDeploymentPlan-ContentsBulkActionsDeploymentPlan.Modal.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ExportContentToDeploymentTarget-ActionDeploymentTarget.Modal.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ExportContentToDeploymentTarget-ContentsBulkActionsDeploymentTarget.Modal.cshtml
  src/OrchardCore.Modules/OrchardCore.Deployment/Views/DeploymentPlan/Display.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/Assets/js/MediaApp/folderComponent.js
  src/OrchardCore.Modules/OrchardCore.Media/Assets/js/MediaApp/mediaItemsGridComponent.js
  src/OrchardCore.Modules/OrchardCore.Media/Assets/js/MediaApp/mediaItemsTableComponent.js
  src/OrchardCore.Modules/OrchardCore.Media/Assets/js/MediaApp/pagerComponent.js
  src/OrchardCore.Modules/OrchardCore.Media/Assets/scss/_main-layout.scss
  src/OrchardCore.Modules/OrchardCore.Media/Assets/scss/_modal-view.scss
  src/OrchardCore.Modules/OrchardCore.Media/Assets/scss/_navbar.scss
  src/OrchardCore.Modules/OrchardCore.Media/Assets/scss/media.scss
  src/OrchardCore.Modules/OrchardCore.Media/Views/Admin/MediaApplication.cshtml
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Scripts/media.js
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Scripts/media.min.js
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Styles/media.css
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Styles/media.min.css
  src/OrchardCore.Modules/OrchardCore.Menu/Views/MenuPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Queries/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Resources/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/trumbowyg-plugins.js
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/trumbowyg-plugins.min.js
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/Admin/Display.cshtml
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/Admin/List.cshtml
  src/OrchardCore.Modules/OrchardCore.Sitemaps/Views/SitemapIndex/List.cshtml
  src/OrchardCore.Modules/OrchardCore.Themes/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Admin/EditPassword.cshtml
  src/OrchardCore.Themes/TheAdmin/Assets.json
  src/OrchardCore.Themes/TheAdmin/Assets/js/menu.js
  src/OrchardCore.Themes/TheAdmin/Assets/js/perfect-scrollbar.js
  src/OrchardCore.Themes/TheAdmin/Assets/scss/TheAdmin.scss
  src/OrchardCore.Themes/TheAdmin/Assets/scss/perfect-scrollbar.css
  src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/NavigationItem-admin.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/NavigationItemLink-admin.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/NavigationItemText.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/UserMenu.cshtml
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Scripts/TheAdmin.min.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
  src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/InputIsDisabledTagHelper.cs
Labels: ready

#7292 Fix FlowPart elements styles
  src/OrchardCore.Modules/OrchardCore.Flows/Assets/scss/flows.edit.scss
  src/OrchardCore.Modules/OrchardCore.Flows/wwwroot/Styles/flows.edit.css
  src/OrchardCore.Modules/OrchardCore.Flows/wwwroot/Styles/flows.edit.min.css
Labels: ready

#7310 Admin menu : Fix icon size and alignment when menu is collapsed.
  src/OrchardCore.Themes/TheAdmin/Assets/scss/TheAdmin.scss
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/TheAdmin.min.css
Labels: ready

#7226 PagerShape anchors "rel" attribute for SEO
  src/OrchardCore.Modules/OrchardCore.Navigation/PagerShapes.cs
  src/docs/reference/modules/Navigation/README.md
Labels: ready

#7299 Add ListContent Permission as Content Type dynamic permission
  src/OrchardCore.Modules/OrchardCore.Contents/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Permissions.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Services/DefaultContentsAdminListFilter.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminList-Filters.cshtml
  src/OrchardCore/OrchardCore.Contents.Core/CommonPermissions.cs
  src/OrchardCore/OrchardCore.Contents.Core/ContentTypePermissionsHelper.cs
Labels: ready

#7202 locale shortcode
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Assets/js/shortcodes.js
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Providers/LocaleShortcodeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/ShortcodeDescriptor-Button-Actions.SummaryAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.Shortcodes/wwwroot/Scripts/shortcodes.js
  src/OrchardCore.Modules/OrchardCore.Shortcodes/wwwroot/Scripts/shortcodes.min.js
  src/docs/reference/modules/Shortcodes/README.md
  test/OrchardCore.Tests/Html/HtmlSanitizerTests.cs
  test/OrchardCore.Tests/Modules/OrchardCore.Shortcodes/LocaleShortcodeTests.cs
Labels: ready

#6243 Add a note to localization module docs
  src/docs/reference/modules/Localize/README.md
Labels: ready

#7409 Bump OpenIddict to 3.0.0-beta6.20527.75
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ApplicationController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Drivers/OpenIdServerSettingsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Recipes/OpenIdServerSettingsStep.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Recipes/OpenIdServerSettingsStepModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Services/OpenIdServerService.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Settings/OpenIdServerSettings.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/CreateOpenIdApplicationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/EditOpenIdApplicationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/OpenIdServerSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/OpenIdServerSettings.Edit.cshtml
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Models/OpenIdToken.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdTokenStore.cs
Labels: OpenId

#7459 Fix email validation when register a new user
  src/OrchardCore.Modules/OrchardCore.Users/Controllers/RegistrationController.cs
  test/OrchardCore.Tests/OrchardCore.Users/RegistrationControllerTests.cs
Labels: ready
