Repository OrchardCMS/OrchardCore, pull requests merged in 2021-05, with the labels that each got.

#8940 Support multiple translation providers
  src/OrchardCore/OrchardCore.Localization.Core/LocalizationManager.cs
  test/OrchardCore.Tests/Localization/LocalizationManagerTests.cs
Labels: localization

#9490 Fix ReCaptcha
  src/OrchardCore.Modules/OrchardCore.ReCaptcha/ReCaptchaLoginFilter.cs
  src/OrchardCore/OrchardCore.ReCaptcha.Core/Services/ReCaptchaService.cs
Labels: security

#9546 Fix Content Type technical name input. (consistency)
  src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/Admin/EditPart.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/ContentPartSettings.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/ContentType.Edit.cshtml
Labels: ready

#9389 Filters for contents list and users list
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Drivers/LocalizationContentsAdminListDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Services/LocalizationPartContentsAdminListFilter.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Services/LocalizationPartContentsAdminListFilterProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Startup.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Views/Items/ContentsAdminFilters-Culture.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/Views/_ViewImports.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Drivers/ContentOptionsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Services/ContentTypeFilterNode.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Services/DefaultContentsAdminListFilter.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Services/DefaultContentsAdminListFilterParser.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Services/DefaultContentsAdminListFilterProvider.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Services/DefaultContentsAdminListQueryService.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Contents/ViewModels/ListContentsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentOptionsViewModel.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminFilters-Card.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsAdminListSearch.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentsAdminFilters-ContentType.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentsAdminFilters-DisplayText.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentsAdminFilters-Sort.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentsAdminFilters-Status.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Taxonomies/Services/TaxonomyContentsAdminListFilter.cs
  src/OrchardCore.Modules/OrchardCore.Users/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserOptionsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Services/DefaultUsersAdminListFilter.cs
  src/OrchardCore.Modules/OrchardCore.Users/Services/DefaultUsersAdminListFilterParser.cs
  src/OrchardCore.Modules/OrchardCore.Users/Services/DefaultUsersAdminListFilterProvider.cs
  src/OrchardCore.Modules/OrchardCore.Users/Services/DefaultUsersAdminListQueryService.cs
  src/OrchardCore.Modules/OrchardCore.Users/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UsersAdminFilters-Email.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UsersAdminFilters-Name.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UsersAdminFilters-Role.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UsersAdminFilters-Sort.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/Items/UsersAdminFilters-Status.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserIndexOptions.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminFilters-Card.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminListSearch.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/_ViewImports.cshtml
  src/OrchardCore/OrchardCore.Contents.Core/OrchardCore.Contents.Core.csproj
  src/OrchardCore/OrchardCore.Contents.Core/Services/ContentItemFilterEngineModelBinder.cs
  src/OrchardCore/OrchardCore.Contents.Core/Services/ContentQueryContext.cs
  src/OrchardCore/OrchardCore.Contents.Core/Services/IContentsAdminListFilter.cs
  src/OrchardCore/OrchardCore.Contents.Core/Services/IContentsAdminListFilterParser.cs
  src/OrchardCore/OrchardCore.Contents.Core/Services/IContentsAdminListFilterProvider.cs
  src/OrchardCore/OrchardCore.Contents.Core/ViewModels/ContentOptionsViewModel.cs
  src/OrchardCore/OrchardCore.Users.Core/OrchardCore.Users.Core.csproj
  src/OrchardCore/OrchardCore.Users.Core/Services/IUsersAdminListFilter.cs
  src/OrchardCore/OrchardCore.Users.Core/Services/IUsersAdminListFilterParser.cs
  src/OrchardCore/OrchardCore.Users.Core/Services/IUsersAdminListFilterProvider.cs
  src/OrchardCore/OrchardCore.Users.Core/Services/UserFilterEngineModelBinder.cs
  src/OrchardCore/OrchardCore.Users.Core/Services/UserQueryContext.cs
  src/OrchardCore/OrchardCore.Users.Core/ViewModels/UserIndexOptions.cs
  src/docs/resources/libraries/README.md
Labels: ready

#9551 Move card / tab shapes to Shape Attributes
  src/OrchardCore.Modules/OrchardCore.Contents/Views/AdminTabs.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Card.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/CardContainer.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Column.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/ColumnContainer.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/LocalNavigation.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/Tab.cshtml
  src/OrchardCore.Modules/OrchardCore.Contents/Views/TabContainer.cshtml
  src/OrchardCore/OrchardCore.DisplayManagement/OrchardCoreBuilderExtensions.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Shapes/GroupShapes.cs
Labels: notready
