Repository OrchardCMS/OrchardCore, pull requests merged in 2021-03, with the labels that each got.

#8637 Add fieldTypeName to Query Schema for GraphQL.
  src/OrchardCore.Modules/OrchardCore.Lucene/GraphQL/LuceneQueryFieldTypeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Sql/GraphQL/SqlQueryFieldTypeProvider.cs
  src/docs/reference/modules/Queries/README.md
Labels: ready

#8800 Custom user filters
  src/OrchardCore.Modules/OrchardCore.Users/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserOptionsDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Services/DefaultUsersAdminListFilter.cs
  src/OrchardCore.Modules/OrchardCore.Users/Services/DefaultUsersAdminListQueryService.cs
  src/OrchardCore.Modules/OrchardCore.Users/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/UsersIndexViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/Views/Admin/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminList.Fields.BulkActions.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminList.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminListBulkActions.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminListCreate.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminListFilters.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminListSearch.cshtml
  src/OrchardCore.Modules/OrchardCore.Users/Views/UsersAdminListSummary.cshtml
  src/OrchardCore/OrchardCore.Users.Core/Indexes/UserByRoleNameIndex.cs
  src/OrchardCore/OrchardCore.Users.Core/OrchardCore.Users.Core.csproj
  src/OrchardCore/OrchardCore.Users.Core/Services/IUsersAdminListFilter.cs
  src/OrchardCore/OrchardCore.Users.Core/Services/IUsersAdminListQueryService.cs
  src/OrchardCore/OrchardCore.Users.Core/ViewModels/UserIndexOptions.cs
Labels: ready

#8306 GraphQL: Add sample codes
  src/docs/reference/core/Apis.GraphQL.Abstractions/README.md
Labels: documentation

#8635 Add support for collections to OpenID Tokens
  src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs
  src/OrchardCore/OrchardCore.Data.Abstractions/StoreCollectionOptions.cs
  src/OrchardCore/OrchardCore.Data/OrchardCoreBuilderExtensions.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Indexes/OpenIdAuthorizationIndex.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Indexes/OpenIdTokenIndex.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Migrations/OpenIdMigrations.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Models/OpenIdAuthorization.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Models/OpenIdToken.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdAuthorizationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdTokenStore.cs
Labels: ready

#8833 Fix liquid parsing for Lucene Queries params
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/AdminController.cs
Labels: ready

#8815 Bump OpenIddict to 3.0.2
  src/OrchardCore.Build/Dependencies.props
Labels: dependencies

#6712 Modifying the Lucene api To accept Post Form Data
  src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/ApiController.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/Model/LuceneQueryModel.cs
Labels: Lucene

#5153 Introduce CultureDictionaryRecordKey for PERF
  src/OrchardCore/OrchardCore.Localization.Abstractions/CultureDictionary.cs
  src/OrchardCore/OrchardCore.Localization.Abstractions/CultureDictionaryRecord.cs
  src/OrchardCore/OrchardCore.Localization.Abstractions/CultureDictionaryRecordKey.cs
  test/OrchardCore.Tests/Localization/CultureDictionaryTests.cs
  test/OrchardCore.Tests/Localization/LocalizationManagerTests.cs
Labels: perf

#8968 Auto enabling Feature dependencies
  src/OrchardCore/OrchardCore.Infrastructure/Shell/ShellDescriptorManager.cs
  src/OrchardCore/OrchardCore/Shell/Descriptor/Settings/ConfiguredFeaturesShellDescriptorManager.cs
  src/OrchardCore/OrchardCore/Shell/Descriptor/Settings/SetFeaturesShellDescriptorManager.cs
  src/OrchardCore/OrchardCore/Shell/ServiceCollectionExtensions.cs
Labels: notready

#8998 Reduce some Liquid tags allocations
  src/OrchardCore.Modules/OrchardCore.Contents/Liquid/ContentAnchorTag.cs
  src/OrchardCore.Modules/OrchardCore.Media/Liquid/MediaAnchorTag.cs
  src/OrchardCore/OrchardCore.DisplayManagement.Liquid/Cache/CacheTag.cs
  src/OrchardCore/OrchardCore.DisplayManagement.Liquid/Tags/AnchorTag.cs
Labels: dontmerge

#8994 Fix OpenIdApplicationStep to include ResponseType rst: permissions
  src/OrchardCore.Modules/OrchardCore.OpenId/Recipes/OpenIdApplicationStep.cs
Labels: OpenId, bug
