Repository OrchardCMS/OrchardCore, pull requests merged in 2021-06, with the labels that each got.

#9370 Check implied permissions
  src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Services/RolesPermissionsHandler.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Security/IPermissionGrantingService.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Security/RoleClaim.cs
  src/OrchardCore/OrchardCore.Infrastructure/Security/AuthorizationHandlers/PermissionHandler.cs
  src/OrchardCore/OrchardCore.Infrastructure/Security/DefaultPermissionGrantingService.cs
  src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs
  test/OrchardCore.Tests/Modules/OrchardCore.Roles/RolesMockHelper.cs
  test/OrchardCore.Tests/Modules/OrchardCore.Roles/RolesPermissionsHandlerTests.cs
  test/OrchardCore.Tests/Security/PermissionHandlerHelper.cs
  test/OrchardCore.Tests/Security/PermissionHandlerTests.cs
Labels: Needs Triage

#9699 Fix Material Design Icons when CDN is disabled.
  package-lock.json
  src/OrchardCore.Modules/OrchardCore.Resources/package-lock.json
  src/OrchardCore.Themes/TheAdmin/Assets.json
  src/OrchardCore.Themes/TheAdmin/ResourceManifestOptionsConfiguration.cs
  src/OrchardCore.Themes/TheAdmin/Startup.cs
  src/OrchardCore.Themes/TheAdmin/Views/Layout-Login.cshtml
  src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml
  src/OrchardCore.Themes/TheAdmin/package-lock.json
  src/OrchardCore.Themes/TheAdmin/package.json
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/images/ui-icons_444444_256x240.png
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/images/ui-icons_555555_256x240.png
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/images/ui-icons_777620_256x240.png
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/images/ui-icons_777777_256x240.png
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/images/ui-icons_cc0000_256x240.png
  src/OrchardCore.Themes/TheAdmin/wwwroot/Styles/images/ui-icons_ffffff_256x240.png
  src/OrchardCore.Themes/TheAdmin/wwwroot/css/TheAdmin.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/css/TheAdmin.min.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-outlined.woff
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-outlined.woff2
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-round.woff
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-round.woff2
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-sharp.woff
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-sharp.woff2
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-two-tone.woff
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons-two-tone.woff2
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons.min.css
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons.woff
  src/OrchardCore.Themes/TheAdmin/wwwroot/fonts/material-icons/material-icons.woff2
  src/OrchardCore.Themes/TheAdmin/wwwroot/js/TheAdmin-header.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/js/TheAdmin-header.min.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/js/TheAdmin.js
  src/OrchardCore.Themes/TheAdmin/wwwroot/js/TheAdmin.min.js
Labels: ready

#9618 HttpRedirectTask - Fixed redirect to PathBase
  src/OrchardCore.Modules/OrchardCore.Workflows/Http/Activities/HttpRedirectTask.cs
Labels: Needs Triage

#9683 UNION and UNION ALL clause support
  src/OrchardCore.Modules/OrchardCore.Queries/Sql/SqlGrammar.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Sql/SqlParser.cs
  test/OrchardCore.Tests/Orchard.Queries/SqlParserTests.cs
Labels: Needs Triage

#9781 Support multipart content type with email service.
  src/OrchardCore.Modules/OrchardCore.Email/Views/Items/EmailTask.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Email/Workflows/Activities/EmailTask.cs
  src/OrchardCore.Modules/OrchardCore.Email/Workflows/Drivers/EmailTaskDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Email/Workflows/ViewModels/EmailTaskViewModel.cs
  src/OrchardCore/OrchardCore.Email.Abstractions/MailMessage.cs
  src/OrchardCore/OrchardCore.Email.Core/Services/SmtpService.cs
Labels: breaking change
