Repository OrchardCMS/OrchardCore, pull requests merged in 2021-04, with the labels that each got.

#9059 Upgrading to YesSql 3
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.ContentTypes/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Contents/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Demo/Controllers/ContentController.cs
  src/OrchardCore.Modules/OrchardCore.Demo/Pages/Foo/Admin/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Html/Migrations.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Title/Migrations.cs
  src/OrchardCore.Modules/OrchardCore.Users/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Activities/CommitTransactionTask.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Controllers/WorkflowTypeController.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentItemsFieldType.cs
  src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs
  src/OrchardCore/OrchardCore.Data.Abstractions/Documents/IDocumentStore.cs
  src/OrchardCore/OrchardCore.Data/Documents/DocumentStore.cs
  src/OrchardCore/OrchardCore.Data/Documents/FileDocumentStore.cs
  src/OrchardCore/OrchardCore.Data/Migration/DataMigrationManager.cs
  src/OrchardCore/OrchardCore.Data/OrchardCore.Data.csproj
  src/OrchardCore/OrchardCore.Infrastructure/Shell/ShellDescriptorManager.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdApplicationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdAuthorizationStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdScopeStore.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdTokenStore.cs
  src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs
  src/docs/resources/libraries/README.md
  test/OrchardCore.Tests/Apis/GraphQL/ContentItemsFieldTypeTests.cs
Labels: dontmerge

#9048 Call Bootstrap make_col with column number for accurate percentages
  gulpfile.js
  package-lock.json
  package.json
  src/OrchardCore.Modules/OrchardCore.AdminDashboard/package-lock.json
  src/OrchardCore.Modules/OrchardCore.AdminMenu/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Markdown/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Media/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Resources/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Setup/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Shortcodes/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Themes/package-lock.json
  src/OrchardCore.Modules/OrchardCore.Workflows/package-lock.json
  src/OrchardCore.Themes/TheAdmin/package-lock.json
  src/OrchardCore.Themes/TheAgencyTheme/package-lock.json
  src/OrchardCore.Themes/TheAgencyTheme/wwwroot/Styles/bootstrap-oc.css
  src/OrchardCore.Themes/TheAgencyTheme/wwwroot/Styles/bootstrap-oc.min.css
  src/OrchardCore.Themes/TheAgencyTheme/wwwroot/scss/modules/_widgets.scss
  src/OrchardCore.Themes/TheBlogTheme/Assets.json
  src/OrchardCore.Themes/TheBlogTheme/package-lock.json
  src/OrchardCore.Themes/TheBlogTheme/package.json
  src/OrchardCore.Themes/TheBlogTheme/wwwroot/css/bootstrap-oc.css
  src/OrchardCore.Themes/TheBlogTheme/wwwroot/css/bootstrap-oc.min.css
  src/OrchardCore.Themes/TheBlogTheme/wwwroot/package-lock.json
  src/OrchardCore.Themes/TheBlogTheme/wwwroot/scss/bootstrap-oc.scss
  src/OrchardCore.Themes/TheBlogTheme/wwwroot/scss/modules/_widgets.scss
  src/OrchardCore.Themes/TheComingSoonTheme/Assets.json
  src/OrchardCore.Themes/TheComingSoonTheme/package-lock.json
  src/OrchardCore.Themes/TheComingSoonTheme/package.json
  src/OrchardCore.Themes/TheComingSoonTheme/wwwroot/css/bootstrap-oc.css
  src/OrchardCore.Themes/TheComingSoonTheme/wwwroot/css/bootstrap-oc.min.css
  src/OrchardCore.Themes/TheComingSoonTheme/wwwroot/package-lock.json
  src/OrchardCore.Themes/TheComingSoonTheme/wwwroot/scss/bootstrap-oc.scss
  src/OrchardCore.Themes/TheComingSoonTheme/wwwroot/scss/modules/_widgets.scss
  src/OrchardCore.Themes/TheTheme/package-lock.json
  src/OrchardCore.Themes/TheTheme/wwwroot/css/bootstrap-oc.css
  src/OrchardCore.Themes/TheTheme/wwwroot/css/bootstrap-oc.min.css
  src/OrchardCore.Themes/TheTheme/wwwroot/scss/modules/_widgets.scss
Labels: dontmerge

#8457 Contents GetAsync: Recall published items (Lombiq Technologies: OCORE-42)
  src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs
  src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManagerSession.cs
Labels: Needs Triage

#9211 Upgrade OpenIddict to 3.0.3
  src/OrchardCore.Build/Dependencies.props
  src/docs/resources/libraries/README.md
Labels: OpenId, dependencies
