Repository OrchardCMS/OrchardCore, pull requests merged in 2022-12, with the labels that each got.

#12510 Move role creation into the recipe instead of feature activation
  src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Models/RolesDocument.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Services/RoleUpdater.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Startup.cs
  src/OrchardCore.Themes/TheAdmin/Recipes/blank.recipe.json
  src/OrchardCore.Themes/TheAdmin/Recipes/headless.recipe.json
  src/OrchardCore.Themes/TheAgencyTheme/Recipes/agency.recipe.json
  src/OrchardCore.Themes/TheBlogTheme/Recipes/blog.recipe.json
  src/OrchardCore.Themes/TheComingSoonTheme/Recipes/comingsoon.recipe.json
  src/OrchardCore.Themes/TheTheme/Recipes/saas.recipe.json
  test/OrchardCore.Tests.Pages/OrchardCore.Application.Pages/Recipes/pages.recipe.json
Labels: breaking change :boom:, Needs Triage

#12932 Introduce AddUsers() extension method
  src/OrchardCore.Modules/OrchardCore.Users/Startup.cs
  src/OrchardCore/OrchardCore.Users.Core/Extensions/UsersServiceCollectionExtensions.cs
Labels: Needs Triage

#12713 Fix FlowPart's Widgets are not indexed in Lucene
  src/OrchardCore.Modules/OrchardCore.Flows/Indexing/FlowPartIndexHandler.cs
  src/OrchardCore.Modules/OrchardCore.Flows/Startup.cs
Labels: enhancement, Lucene

#12804 Migrate the OpenID module to OpenIddict 4.0
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdValidationConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/OpenIdExtensions.cs
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdApplicationStore.cs
Labels: OpenId
