Repository OrchardCMS/OrchardCore, pull requests merged in 2022-09, with the labels that each got.

#11130 Remove localization workaround in Data Annotation Attributes
  src/OrchardCore.Modules/OrchardCore.Users/Controllers/RegistrationController.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ChangePasswordViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/RegisterViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ResetPasswordViewModel.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Email/EmailAddressAttribute.cs
Labels: Needs Triage

#10935 Archive Later functionality (Lombiq Technologies: OCORE-72)
  OrchardCore.sln
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Assets.json
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Assets/scss/archive-later.scss
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Drivers/ArchiveLaterPartDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Indexes/ArchiveLaterPartIndex.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Indexes/ArchiveLaterPartIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Manifest.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Migrations.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Models/ArchiveLaterPart.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/OrchardCore.ArchiveLater.csproj
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Services/ScheduledArchivingBackgroundTask.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Startup.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/ViewModels/ArchiveLaterPartViewModel.cs
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Views/ArchiveLaterPart.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Views/ArchiveLaterPart.Option.cshtml
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Views/ArchiveLaterPart.SummaryAdmin.cshtml
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/Views/_ViewImports.cshtml
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/wwwroot/Styles/archive-later.css
  src/OrchardCore.Modules/OrchardCore.ArchiveLater/wwwroot/Styles/archive-later.min.css
  src/OrchardCore/OrchardCore.Application.Cms.Core.Targets/OrchardCore.Application.Cms.Core.Targets.csproj
Labels: Needs Triage

#9087 GraphQL 4
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Extensions/DocumentWriterExtensions.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLRequest.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/OrchardCore.Apis.GraphQL.csproj
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/OrchardFieldNameConverter.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/RequestServicesDependencyResolver.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Services/SchemaService.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/ValidationRules/MaxNumberOfResultsValidationRule.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/ValidationRules/RequiresPermissionValidationRule.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Fields/ContentFieldsProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Fields/ObjectGraphTypeFieldProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Types/ContentPickerFieldQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Types/HtmlFieldQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.ContentLocalization/GraphQL/LocalizationQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Demo/Services/UserProfileClaimsProvider.cs
  src/OrchardCore.Modules/OrchardCore.Html/GraphQL/HtmlBodyQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Layers/GraphQL/LayerQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Layers/GraphQL/SiteLayersQuery.cs
  src/OrchardCore.Modules/OrchardCore.Lists/GraphQL/ListQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Localization/GraphQL/SiteCulturesQuery.cs
  src/OrchardCore.Modules/OrchardCore.Lucene/GraphQL/LuceneQueryFieldTypeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Markdown/GraphQL/MarkdownBodyQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Markdown/GraphQL/MarkdownFieldQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Media/GraphQL/MediaAssetObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Media/GraphQL/MediaAssetQuery.cs
  src/OrchardCore.Modules/OrchardCore.Media/GraphQL/MediaFieldQueryObjectType.cs
  src/OrchardCore.Modules/OrchardCore.Queries/Sql/GraphQL/SqlQueryFieldTypeProvider.cs
  src/OrchardCore.Modules/OrchardCore.Taxonomies/GraphQL/TaxonomyFieldQueryObjectType.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/Extensions/DataLoaderExtensions.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/Extensions/FieldBuilderResolverExtensions.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/Extensions/PermissionsExtensions.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/Extensions/ResolveFieldContextExtensions.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/GraphQLSettings.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/GraphQLUserContext.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/OrchardCore.Apis.GraphQL.Abstractions.csproj
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/Queries/WhereInputObjectGraphType.cs
  src/OrchardCore/OrchardCore.Apis.GraphQL.Abstractions/Resolvers/LockedAsyncFieldResolver.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Extensions/DataLoaderExtensions.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Extensions/FieldTypeExtensions.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentItemQuery.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentItemsFieldType.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/GraphQLFilter.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/IGraphQLFilter.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/ContentItemType.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/DynamicContentTypeBuilder.cs
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/TypedContentTypeBuilder.cs
  src/docs/resources/libraries/README.md
  test/OrchardCore.Tests/Apis/GraphQL/Blog/BlogPostTests.cs
  test/OrchardCore.Tests/Apis/GraphQL/ContentItemsFieldTypeTests.cs
  test/OrchardCore.Tests/Apis/GraphQL/ValidationRules/RequiresPermissionValidationRuleTests.cs
Labels: notready, GraphQL

#9569 Make PortableObjectStringLocalizer simpler for inheritance
  src/OrchardCore/OrchardCore.Localization.Core/PortableObject/PortableObjectStringLocalizer.cs
Labels: Needs Triage

#12333 React to localization workaround removal for data annotations attributes
  src/OrchardCore.Modules/OrchardCore.Email/ViewModels/SmtpSettingsViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/UrlAttribute.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/CreateOpenIdApplicationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/EditOpenIdApplicationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ChangeEmailViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/EditUserInformationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ForgotPasswordViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/ViewModels/LinkExternalLoginViewModel.cs
  test/OrchardCore.Tests/Modules/OrchardCore.OpenId/ApplicationControllerTests.cs
Labels: Needs Triage

#12306 Add scope to client credentials token
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs
Labels: OpenId

#10570 Keep file name of attached media files
  src/OrchardCore.Modules/OrchardCore.Media/Assets/js/MediaField/attachedMediaField.js
  src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Media/Drivers/MediaFieldDriver.cs
  src/OrchardCore.Modules/OrchardCore.Media/Fields/MediaFieldAttachedFileNameExtensions.cs
  src/OrchardCore.Modules/OrchardCore.Media/ViewModels/EditMediaFieldViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Scripts/media.js
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Scripts/media.min.js
Labels: Needs Triage
