Repository OrchardCMS/OrchardCore, pull requests merged in 2023-07, with the labels that each got.

#14013 Enable the "plain" code challenge method by default
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs
Labels: enhancement, OpenId

#13680 Improving workflows page load time (Lombiq Technologies: NEST-410)
  src/OrchardCore.Modules/OrchardCore.Workflows/Controllers/WorkflowController.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Controllers/WorkflowTypeController.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/ViewModels/WorkflowTypeIndexViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/WorkflowType/Index.cshtml
Labels: Needs Triage

#12548 Add text field default value field to settings model and display it in settings edit view
  src/OrchardCore.Modules/OrchardCore.ContentFields/Drivers/TextFieldDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Settings/TextFieldSettings.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Views/TextFieldSettings.Edit.cshtml
Labels: dontmerge, Needs Steering

#14019 Remove invalid null checks from OpenIdTokenStore
  src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdTokenStore.cs
Labels: bug :bug:, OpenId

#13918 Do not change the tenant state while importing partial recipe
  src/OrchardCore.Modules/OrchardCore.Recipes/Controllers/AdminController.cs
Labels: Needs Triage
