Repository OrchardCMS/OrchardCore, pull requests merged in 2023-11, with the labels that each got.

#14686 Fix for missing claims when using OpenID Server authorization code flow.
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs
Labels: bug :bug:, OpenId

#14652 Add a way to Remove User from a Role (Issue #14632)
  src/OrchardCore.Modules/OrchardCore.Roles/OrchardCore.Roles.csproj
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Items/GetUsersByRoleTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Items/GetUsersByRoleTask.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Items/GetUsersByRoleTask.Fields.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Items/UnassignUserRoleTask.Fields.Design.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Items/UnassignUserRoleTask.Fields.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Items/UnassignUserRoleTask.Fields.Thumbnail.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Shared/Components/SelectRoles/Default.cshtml
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Workflows/Activities/GetUsersByRoleTask.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Workflows/Activities/UnassignUserRoleTask.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Workflows/Drivers/GetUsersByRoleTaskDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Workflows/Drivers/UnassignUserRoleTaskDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Workflows/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Workflows/ViewModels/GetUsersByRoleTaskViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Views/Workflows/ViewModels/UnassignUserRoleTaskViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/Liquid/UsersByIdFilter.cs
Labels: Needs Triage

#14372 Add As/Put method to ISite to allow caching
  src/OrchardCore.Modules/OrchardCore.Media/Processing/MediaTokenOptionsConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.Settings/SiteSettings.cs
  src/OrchardCore/OrchardCore.Data.Abstractions/Documents/Document.cs
  src/OrchardCore/OrchardCore.Data.Abstractions/Documents/IDocument.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Documents/DocumentEntity.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Entities/Entity.cs
  src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/ISite.cs
  src/OrchardCore/OrchardCore.Infrastructure/Documents/DocumentManager.cs
  test/OrchardCore.Tests/Modules/OrchardCore.Media/MediaTokenTests.cs
  test/OrchardCore.Tests/OrchardCore.Users/RegistrationControllerTests.cs
  test/OrchardCore.Tests/Utilities/SiteMockHelper.cs
Labels: Needs Triage

#14673 Update AngleSharp 1.0.6
  src/OrchardCore.Build/Dependencies.props
  src/docs/resources/libraries/README.md
Labels: dontmerge
