Repository OrchardCMS/OrchardCore, pull requests merged in 2024-07, with the labels that each got.

#16379 Fixes missing dependencies in the ShellBlueprint
  src/OrchardCore/OrchardCore/Extensions/ExtensionManager.cs
Labels: needs triage

#16351 Remove set as startup task button for non-event activities
  src/OrchardCore.Modules/OrchardCore.Workflows/Views/Activity.Design.cshtml
Labels: don't merge

#16467 OpenId UI Enhancements
  src/OrchardCore.Modules/OrchardCore.Media/Assets.json
  src/OrchardCore.Modules/OrchardCore.Media/Assets/js/helpers.js
  src/OrchardCore.Modules/OrchardCore.Media/ResourceManifestOptionsConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Scripts/media.js
  src/OrchardCore.Modules/OrchardCore.Media/wwwroot/Scripts/media.min.js
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ApplicationController.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/ViewModels/OpenIdApplicationsIndexViewModel.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Application/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/OpenIdClientSettings.Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Scope/Create.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Scope/Edit.cshtml
  src/OrchardCore.Modules/OrchardCore.OpenId/Views/Scope/Index.cshtml
  src/OrchardCore.Modules/OrchardCore.Resources/Assets.json
  src/OrchardCore.Modules/OrchardCore.Resources/Assets/js/credential-helpers.js
  src/OrchardCore.Modules/OrchardCore.Resources/ResourceManagementOptionsConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/credential-helpers.js
  src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/credential-helpers.min.js
Labels: enhancement, OpenId
