Repository OrchardCMS/OrchardCore, pull requests merged in 2024-03, with the labels that each got.

#15453 Update OpenIddict 5.3.0
  src/OrchardCore.Build/Dependencies.props
  src/docs/resources/libraries/README.md
Labels: OpenId, dependencies

#15460 Configure JsonOptions by default
  src/OrchardCore/OrchardCore.Abstractions/Json/Extensions/JsonSerializerOptionsExtensions.cs
  src/OrchardCore/OrchardCore.Abstractions/Json/JsonOptionsConfigurations.cs
  src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs
Labels: Needs Triage

#15457 Author field perhaps is null
  src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/ContentItemInterface.cs
Labels: Needs Triage

#15364 Fix log file path based on ORCHARD_APP_DATA environment variable
  src/OrchardCore.Cms.Web/NLog.config
  src/OrchardCore/OrchardCore.Abstractions/ShellOptionConstants.cs
  src/OrchardCore/OrchardCore.Logging.NLog/HostBuilderExtensions.cs
  src/OrchardCore/OrchardCore.Logging.NLog/WebHostBuilderExtensions.cs
  src/OrchardCore/OrchardCore/Shell/ShellOptionsSetup.cs
  src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Web/NLog.config
  src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Web/appsettings.json
Labels: Needs Triage

#10641 Update OpenId module, write more information to log
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdClientConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs
  src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdValidationConfiguration.cs
Labels: enhancement, OpenId

#15529 Fix graphql api with parameters
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLNamedQueryRequest.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Json/GraphQLNamedQueryRequestJsonConverter.cs
  src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Startup.cs
Labels: Needs Triage

#15524 Use JsonPath.Net for JSONPath selectors (Lombiq Technologies: OCORE-148)
  src/OrchardCore.Build/Dependencies.props
  src/OrchardCore.Modules/OrchardCore.Menu/Controllers/AdminController.cs
  src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JArray.cs
  src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs
  src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JObject.cs
  src/OrchardCore/OrchardCore.Abstractions/OrchardCore.Abstractions.csproj
  test/OrchardCore.Tests/Data/ContentItemTests.cs
Labels: Needs Triage

#15509 Add SelectNode and Remove method to JsonDynamicObject class
  src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicArray.cs
  src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicObject.cs
  test/OrchardCore.Tests/Data/ContentItemTests.cs
Labels: Needs Triage

#14366 Named Part Fields are not indexed
  src/OrchardCore.Modules/OrchardCore.ContentFields/Extensions/ContentPartFieldDefinitionExtensions.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/BooleanFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/ContentPickerFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/DateFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/DateTimeFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/HtmlFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/LinkFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/MultiTextFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/NumericFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/TextFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/TimeFieldIndexProvider.cs
  src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/UserPickerFieldIndexProvider.cs
Labels: Needs Triage
