Repository OrchardCMS/OrchardCore, pull requests merged in 2024-02, with the labels that each got.

#10939 Make NullStringLocalizer & HtmlLocalizer Public
  src/OrchardCore/OrchardCore/Localization/NullHtmlLocalizer.cs
  src/OrchardCore/OrchardCore/Localization/NullHtmlLocalizerFactory.cs
  src/OrchardCore/OrchardCore/Localization/NullStringLocalizer.cs
  src/OrchardCore/OrchardCore/Localization/NullStringLocalizerFactory.cs
  test/OrchardCore.Tests/Localization/NullHtmlLocalizerTests.cs
  test/OrchardCore.Tests/Localization/NullStringLocalizerTests.cs
Labels: Needs Triage

#15113 Fix errors when role names have different casing
  src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Services/RoleStore.cs
  src/OrchardCore.Modules/OrchardCore.Roles/Services/RoleUpdater.cs
  src/OrchardCore.Modules/OrchardCore.Users/Drivers/RoleLoginSettingsDisplayDriver.cs
  src/OrchardCore.Themes/TheAdmin/Recipes/headless.recipe.json
Labels: Needs Triage

#12954 Remove useless placeholder file
  src/OrchardCore.Themes/TheTheme/PlaceHolder.cs
Labels: Needs Triage

#13181 User Localization settings
  src/OrchardCore.Modules/OrchardCore.Users/Localization/Drivers/UserLocalizationDisplayDriver.cs
  src/OrchardCore.Modules/OrchardCore.Users/Localization/Extensions/ClaimsPrincipleExtensions.cs
  src/OrchardCore.Modules/OrchardCore.Users/Localization/Models/UserLocalizationSettings.cs
  src/OrchardCore.Modules/OrchardCore.Users/Localization/Providers/UserLocalizationClaimsProvider.cs
  src/OrchardCore.Modules/OrchardCore.Users/Localization/Providers/UserLocalizationRequestCultureProvider.cs
  src/OrchardCore.Modules/OrchardCore.Users/Localization/Startup.cs
  src/OrchardCore.Modules/OrchardCore.Users/Localization/UserLocalizationConstants.cs
  src/OrchardCore.Modules/OrchardCore.Users/Localization/ViewModel/UserLocalizationViewModel.cs
  src/OrchardCore.Modules/OrchardCore.Users/Manifest.cs
  src/OrchardCore.Modules/OrchardCore.Users/Views/UserCulture.Edit.cshtml
  src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs
  src/docs/reference/modules/Users/README.md
  src/docs/releases/1.9.0.md
Labels: ready

#15324 Decorate the interactive OpenID endpoints with `[DisableCors]`
  src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs
Labels: enhancement, OpenId, security

#15329 Update Microsoft.Extensions.Http.Resilience 8.2.0
  src/OrchardCore.Build/Dependencies.props
Labels: merge conflict

#15247 DisplayAsync to return actual pre-rendered IHtmlContent
  src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DisplayHelper.cs
  src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Shapes/Shape.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Theming/ThemeLayout.cs
  src/OrchardCore/OrchardCore.DisplayManagement/Views/ShapeViewModel.cs
Labels: Needs Triage
